# Generated by Django 4.2.3 on 2023-07-15 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_alter_user_watchlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to="auctions.category",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="imageURL",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
