# Generated by Django 4.2.3 on 2023-07-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_listing_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="og_price",
            field=models.FloatField(default=100, max_length=10),
            preserve_default=False,
        ),
    ]
