# Generated by Django 4.2.3 on 2023-07-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_remove_post_likes_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dark_mode",
            field=models.BooleanField(
                default=True, verbose_name="Dark Mode Preference"
            ),
        ),
    ]
